# For문

```{r}
for (i in 1:10) {
  print(i)
}
```

```{r}
for(i in c(1,3,5)){
  print(i)
}
```

1\~100까지의 홀수만 출력하기

```{r}
for(i in seq(1,100,2)){
  print(i)
}
```

```{r}
a <- vector()
for(i in 1:10){
  cat(paste(i," => ",sqrt(i),"\n"))
}
```

1부터 100까지의 짝수의 합계 구하기

```{r}
data <- 1:100
sum <- 0
sumIfelse <- 0
for(i in data){
  if(i %% 2 ==0){
  sum <- sum(sum,i)
  }
}
sum

sum(sumIfelse,ifelse(data %% 2,0,data))


```

```{r}
excel <- read.csv("./Data/excel.csv")
head(excel)
```

```{r}
data <- excel$q3
sumEven <- sumOdd <- 0

for (i in data) {
  if(i %% 2 == 0){
    sumEven = sumEven+i
  }else{
    sumOdd = sumOdd+i
  }
    
}

cat("홀수의 합은",sumOdd,"이고 짝수의 합은",sumEven)
```

```{r}
for(i in 1:9){
  cat("2 X",i,"=",2*i,"\n")
}
```

```{r}
gugu <- function(){
  for(i in 1:9){
  cat("2 X",i,"=",2*i,"\n")
  }
}
gugu()
```

```{r}
gugu2 <- function(a){
  for(i in 1:9){
  cat(a," X",i,"=",a*i,"\n")
  }
}
gugu2(3)
  
```

```{r}
gugu3 <- function(a,b){
  for(i in 1:b){
  cat(a," X",i,"=",a*i,"\n")
  }
}
gugu3(2,12)
```

```{r}
gugu4 <- function(a){
  for(i in seq(2,a,2)){
    for(j in seq(2,a,2)){
      cat(i,"X",j,"=",i*j,"\n")
    }
    cat("-------------------\n")
  }
}
gugu4(8)
```

```{r}
score <- c(85,95,89)
name <- c("유비","관우","장비")

j <- 1
for(i in score){
  cat(name[j], ":", i, "\n")
  j=j+1
}

cat(paste(name,":",score,"\n"),sep = "")
```

## while

```{r}
i <- 0
while(i <10){
  i = i + 1
  print(i)
}
```

```{r}
i <- 0
while(T){
  i = i +1
  print(i)
  if(i>9){
    break
  }
}
```

## repeat

```{r}
i <- 0
repeat{
  i = i + 1
  if(i>10){
    break
  }
  print(i)
}
```
