# 시뮬레이션

동전의 앞면 뒷면 시뮬레이션

몬테카를로 시뮬레이션

```{r}
x <- runif(1)
if(x <= 1/2){
  result = 0
}else{
  result = 1
}
print(result)
```

```{r}
coin <- function(n){
  count1 = 0
  count2 = 0
  
  for( i in 1:n){
    if(runif(1) <= 1/2){
      count1 = count1 + 1
    }else{
      count2 = count2 + 1
    }
  }
  cat("front : ",count1,"\n")
  cat("back : ",count2,"\n")
  cat("----------------------\n")
}

```

```{r}
coin(10)
coin(100)
coin(1000)
coin(10000)
coin(100000)
```

가위,바위,보

```{r}
rock <- function(n){
  
  p1 <- 0
  p2 <- 0
  win <- 0
  drew <- 0
  lose <- 0
  for (i in 1:n){
    p1 <- trunc((runif(1,1,4)))
    p2 <- trunc((runif(1,1,4)))
    if(p1 > p2){
      win <- win + 1
    }else if(p1 == p2){
      drew <- drew + 1
    }else{
      lose <- lose + 1
    }
  }
  cat("win : ",win,"\n")
  cat("drew : ",drew,"\n")
  cat("lose : ",lose,"\n")
  cat("-----------------------\n")
}
```

```{r}
rock <- function(n){
  scissor = 0
  rock = 0
  paper = 0
  for(i in 1 : n){
    x <- trunc(runif(1) * 3) + 1
    if(x == 1) scissor = scissor + 1
    if(x == 2) rock = rock + 1
    if(x == 3) paper = paper + 1
  }
  cat("가위 : \t", scissor, "\n")
  cat("바위 : \t", rock, "\n")
  cat("보 : \t", paper, "\n")
  cat("-----------------------\n")
}
```

```{r}

rock(10)
rock(100)
rock(1000)
rock(10000)
rock(100000)
rock(1000000)
```

## 주사위 시뮬레이션

```{r}
dice <- function(n){
 diceFace <- rep(0,6)
 cat("Throw : ",n,"\n")
  for(i in 1:n){
    x <- trunc(runif(1) * 6) + 1
    diceFace[x]= diceFace[x] + 1
  }
  for(j in 1:length(diceFace)){
    cat("No",j,"=>",diceFace[j],"\n")
  }
 cat("---------------\n")
}
```

```{r}

options(scipen = 100)
dice(10)
dice(100)
dice(1000)
dice(10000)
dice(100000)
dice(1000000)
```
