# 서울 열린 데이터관장(교통사고 구별, 월별) 검색 후 분석가능하게 정제하기

결측치 삭제

```{r}
library(plotrix)
library(dplyr)
library(stringr)
traffic <- read.table("./Data/trafficAccident_2011_2019.txt",header = T)
traffic <- traffic[-c(1:3),]
traffic[,4:15]
traffic <- traffic[,-4]
for(i in 4:15){
  traffic[,i] <- str_replace_all(traffic[,i],"-","0")
  traffic[,i] <- str_replace_all(traffic[,i],",","")
  traffic[,i] <- as.numeric(traffic[,i])
}
traffic[,4] <- str_replace_all(traffic[,4],",","")
traffic <- traffic[!(traffic$자치구별 == "합계"),]
traffic

```

하나 돌려보기

```{r}
test <- as.data.frame(t(traffic[1:3,4:15])) 
test
colnames(test) <- c("발생건수","사망자수","부상자수")
test
rownames(test) <- c()
test
test <-data_frame(년도 = traffic[1,1], 월 = 1:12, 자치구명 = traffic[1,2],test)
test
rownames(test)
```

한번에 돌려보기

```{r}

for (i in seq(4,nrow(traffic),3)) {
  test2 <- as.data.frame(t(traffic[i:(i+2),4:15])) 
  colnames(test2) <- c("발생건수","사망자수","부상자수")
  test2 <-data.frame(년도 = traffic[i,1], 월 = 1:12, 자치구명 = traffic[i,2],test2)
  rownames(test2) <- c()
  test <- rbind(test,test2)
}
for (i in 4:6) {
  test[,i] <- as.numeric(as.matrix(test[,i]))  
}
test
traffic <- test
```

레퍼런스 소스와 비교

```{r}
copy<-read.csv("./Data/newSeoul2019.csv")
copy
traffic
sum(copy$월) ==sum(traffic$월)

setdiff(traffic,copy)
```

산포도 확인

```{r}
par(family = "AppleGothic")
plot(traffic$발생건수,traffic$부상자수)
```

# 선생님버전

```{r}
seoul <- read.table("./Data/trafficAccident_2011_2019.txt",header = T)
head(seoul,12)
```

필요없는 럴럼과 열 제거

```{r}
seoul <- seoul[-c(1:3),-4]
```

NA확인

```{r}
for(i in 1: ncol(seoul)){
  print(sum(is.na(seoul[,i])))
}
```

컬럼 이름 정리

```{r}
colnames(seoul) <- c("기간",'자치구별','구분',paste(1:12,'월',sep=""))
seoul
```

```{r}
rownames(seoul)<- c()
tail(seoul)
```

현재 DataSet의 row수 계산

```{r}
9 * 3 * 25
```

컬럼별 Data확인

```{r}
unique(seoul$기간)
```

```{r}
unique(seoul$자치구별)
```

```{r}
unique(seoul$구분)
```

합계를 제거

자치구별에 합계라고 되어있는 row제거

```{r}
row_hap <-  as.numeric(rownames(subset(seoul,자치구별 == "합계")))
seoul <- seoul[-row_hap,]
nrow(seoul)
```

```{r}
length(unique(seoul$자치구별)) 
```

\-\--

# 전처리하여 new DataFrame 만들기

```{r}
9 * 25 * 12
```

```{r}

년도 <- rep(2011:2019,each =(300))
월 <- rep(1:12, 9*25)
자치구명 <- rep(rep(unique(seoul$자치구별), each=12),9)
length(자치구명)
length(년도)
length(월)
```

새로운 DataFrame 제작

```{r}
newSeoul <- data.frame(년도,월,자치구명)
newSeoul
```

기존 data를 new format에 맞추기

```{r}
temp <- c()
for(i in seq(1,673,3)){
 temp <- rbind(temp,t(seoul[i:(i+2),4:ncol(seoul)]))

}
```

```{r}
rownames(temp) <- c()
tail(temp)
```

```{r}
newSeoul <- cbind(newSeoul,temp)
head(newSeoul)
```

newSeoul의 컬럼 이름 변경

```{r}
colnames(newSeoul) <- c('년도', '월', '자치구명','발생건수','사망자수','부상자수')
head(newSeoul)
```

\-\--

# newSeoul 정제하기

na확인

```{r}
for(i in 1: ncol(newSeoul)){
  print(sum(is.na(newSeoul[,i])))
}
```

내부구조

```{r}
str(newSeoul)
```

각 열의 -을 0으로 변경하기

```{r}
library(stringr)
```

```{r}
for (i in 4:ncol(newSeoul)) {
  newSeoul[,i] <- str_replace_all(newSeoul[,i],"-",'0')
}
str(newSeoul)
```

천단위 쉼표를 제거

```{r}
for (i in 4:ncol(newSeoul)) {
  newSeoul[,i] <- str_remove_all(newSeoul[,i],",")
}

```

월Data읠 Type을 숫자로 변경

```{r}
for (i in 4:ncol(newSeoul)) {
  newSeoul[,i] <- as.numeric(newSeoul[,i])
}
str(newSeoul)
```

```{r}
newSeoul
```

저장하기

```{r}
write.csv(newSeoul,"./Data/newSeoul.csv",row.names = F)
```

데이터 확인 작업

```{r}
plot(newSeoul$발생건수,newSeoul$부상자수)
```
