---
---
---

# 서울시 최근 5년 인구감소에 따른 월세 추세 분석

```{r}
library(plotrix)
library(dplyr)
library(stringr)
```

### 월세통계

2011-2021까지 따로 만들기

```{r}
seoul_rent_2011 <- read.csv("./Data/seoul_home_rent_2011~2021/seoul_home_rent_2011.txt",fileEncoding = "euckr")
head(seoul_rent_2011)
seoul_rent_2011 <-seoul_rent_2011[,-c(2,4,5:11,13,16:23)]
seoul_rent_2011 <- subset(seoul_rent_2011,seoul_rent_2011$전월세구분 == "월세")
seoul_rent_2011 <- seoul_rent_2011[,-c(3)]
colnames(seoul_rent_2011) <- c('년도','자치구','보증금','월세')
head(seoul_rent_2011)


```

### 년도별 자치구 월세 평균

```{r}
seoul_rent_2011 <-aggregate(월세~자치구,seoul_rent_2011,mean)

seoul_rent_2011$월세 <- round(seoul_rent_2011$월세,2)

seoul_rent_2011 <- as.data.frame(t(seoul_rent_2011))
colnames(seoul_rent_2011) <- seoul_rent_2011[1,] 
seoul_rent_2011 <- seoul_rent_2011[-1,]
seoul_rent <- seoul_rent_2011
seoul_rent
```

### 2011-2021년 데이터 합치기

```{r}

for (i in 2012:2021) {
  
  seoul_rent_cbind <- read.csv(paste0("./Data/seoul_home_rent_2011~2021/seoul_home_rent_",i,".txt"),fileEncoding = "euckr")
seoul_rent_cbind <-seoul_rent_cbind[,-c(2,4,5:11,13,16:23)]
seoul_rent_cbind <- subset(seoul_rent_cbind,seoul_rent_cbind$전월세구분 == "월세")
seoul_rent_cbind <- seoul_rent_cbind[,-c(3)]
colnames(seoul_rent_cbind) <- c('년도','자치구','보증금','월세')
seoul_rent_cbind <-aggregate(월세~자치구,seoul_rent_cbind,mean)

seoul_rent_cbind$월세 <- round(seoul_rent_cbind$월세,2)

seoul_rent_cbind <- as.data.frame(t(seoul_rent_cbind))
colnames(seoul_rent_cbind) <- seoul_rent_cbind[1,] 
seoul_rent_cbind <- seoul_rent_cbind[-1,]
seoul_rent <- rbind(seoul_rent,seoul_rent_cbind)
}

rownames(seoul_rent) <- c(2011:2021)

for(i in 1:25){
seoul_rent[,i] <- as.numeric(seoul_rent[,i])
}
seoul_rent
```

## 월세평균 top5

```{r}
seoul_rent_5year <- as.data.frame(t(seoul_rent)) 
seoul_rent_5year <- arrange(seoul_rent_5year,desc(seoul_rent_5year$`2021`))

seoul_rent_top5 <-as.data.frame(t(head(seoul_rent_5year,5)))[7:11,]
seoul_rent_top5
```

```{r}
par(family = "AppleGothic")

plot(seoul_rent_top5$강남구 ~ rownames(seoul_rent_top5),
     type = "l",
     ylim = c(60,max(seoul_rent_top5)),
     main = "서울시 자치구별 월세평균 top5",
     col = "red",
     ylab = "월세 (단위:만원)",
     xlab = "년도",
        las=1
     )
lines(seoul_rent_top5$서초구 ~ rownames(seoul_rent_top5),
      type = "l",
     col = "blue"
)
lines(seoul_rent_top5$용산구 ~ rownames(seoul_rent_top5),
      type = "l",
     col = "green"
)
lines(seoul_rent_top5$성동구 ~ rownames(seoul_rent_top5),
      type = "l",
     col = "purple"
)
lines(seoul_rent_top5$중구 ~ rownames(seoul_rent_top5),
      type = "l",
     col = "orange"
)
legend(2017,110,
  c('강남구','서초구','용산구','성동구','중구'),
  col = c("red",'blue','green','purple','orange'),
  lty = c(1,1,1,1,1),
  cex = 0.7
)
```

## 월세평균 wost5

```{r}
seoul_rent_5year <- as.data.frame(t(seoul_rent)) 
seoul_rent_5year <- arrange(seoul_rent_5year,desc(seoul_rent_5year$`2021`))

seoul_rent_wost5 <-as.data.frame(t(tail(seoul_rent_5year,5)))[7:11,]
seoul_rent_wost5
```

```{r}
par(family = "AppleGothic")

plot(seoul_rent_wost5$금천구 ~ rownames(seoul_rent_wost5),
     type = "l",
     ylim = c(35,max(seoul_rent_wost5)),
     main = "서울시 자치구별 월세평균 worst5",
     col = "red",
     ylab = "월세 (단위:만원)",
     xlab = "년도",
        las=1
     )
lines(seoul_rent_wost5$구로구 ~ rownames(seoul_rent_wost5),
      type = "l",
     col = "blue"
)
lines(seoul_rent_wost5$강북구 ~ rownames(seoul_rent_wost5),
      type = "l",
     col = "green"
)
lines(seoul_rent_wost5$관악구 ~ rownames(seoul_rent_wost5),
      type = "l",
     col = "purple"
)
lines(seoul_rent_wost5$중랑구 ~ rownames(seoul_rent_wost5),
      type = "l",
     col = "orange"
)
legend(2020,38,
  c('금천구','구로구','강북구','관악구','중랑구'),
  col = c("red",'blue','green','purple','orange'),
  lty = c(1,1,1,1,1),
  cex = 0.7
)
```

## 년도별 이사건수 및 인구증가율

2017-2021 이사건수 데이터 합치기

```{r}

seoul_rent_cnt <- nrow(read.csv("./Data/seoul_home_rent_2011~2021/seoul_home_rent_2017.txt",fileEncoding = "euckr"))

for (i in 2018:2021) {
  seoul_rent_cnt2 <- nrow(read.csv(paste0("./Data/seoul_home_rent_2011~2021/seoul_home_rent_",i,".txt"),fileEncoding = "euckr"))
seoul_rent_cnt <- append(seoul_rent_cnt,seoul_rent_cnt2)  
}
seoul_rent_cnt <- as.data.frame(seoul_rent_cnt)
rownames(seoul_rent_cnt) <- c(2017:2021)
colnames(seoul_rent_cnt) <- c("이사건수")
seoul_rent_cnt

```

```{r}
par(family = "AppleGothic")
options(scipen = 100)
plot(seoul_rent_cnt$이사건수/10000 ~ rownames(seoul_rent_cnt),
        ylim = c(40,max(seoul_rent_cnt$이사건수)/10000),
        ylab = "이사건수 (단위 :만건)",
        xlab = "년도",
        main = "2017~2021년 서울시 이사건수",
        type = "l",
        las=1,
     col = 'red'
        )
```

## 서울시 1인가구 증가율

#### **서울시 1인가구(연령별) 통계**

자료출처 : 서울열린데이터광장

<http://data.seoul.go.kr/dataList/10995/S/2/datasetView.do>

```{r}
seoul_one_home <- read.csv("./Data/seoul_home_rent_2011~2021/seoul_1home.csv")
seoul_one_home <- arrange(seoul_one_home,seoul_one_home$시점)
seoul_one_home <- seoul_one_home[-c(1:3),]
rownames(seoul_one_home) <- c(2017:2021)
seoul_one_home
```

```{r}
par(family = "AppleGothic")
plot(seoul_one_home$합계/10000 ~ rownames(seoul_one_home),
     type = "l",
     main = "2017~2021 서울시 1인가구",
     ylab = "가구수(단위:만)",
     xlab = "년도",
        las=1,
     col = 'red'
     )


```

## 서울시 인구

참조통계

kosis : **행정구역(시군구)별, 성별 인구수**

```{r}
seoul_popul <- read.csv("./Data/seoul_home_rent_2011~2021/seoul_ population_2016_2021.csv",fileEncoding = 'euckr')[-c(1,2),]

seoul_popul <- seoul_popul[,-c(2:4)]
seoul_popul <- as.data.frame(t(seoul_popul))
colnames(seoul_popul) <- seoul_popul[1,]
seoul_popul <- seoul_popul[-1,]
rownames(seoul_popul) <- c(2016:2021)


```

데이터 돌리기

```{r}
for (i in 1:25) {
seoul_popul[,i] <-  as.numeric(seoul_popul[,i])   
}
```

## 서울시 총인구

```{r}
seoul_popul_2016_2021 <- seoul_popul[-1,]
seoul_popul_total <- c()
for (i in 1:5) {
seoul_popul_total <- append(seoul_popul_total,sum(seoul_popul_2016_2021[i,])  )
}
seoul_popul_total <- as.data.frame(seoul_popul_total)
colnames(seoul_popul_total) <- c("서울시")
rownames(seoul_popul_total) <- rownames(seoul_popul_2016_2021)
seoul_popul_total

```

```{r}
par(family = "AppleGothic")
plot(seoul_popul_total$서울시/10000~rownames(seoul_popul_total),
     type = "l",
     main = "2017~2021 서울시 총 인구수",
     ylab = "인구수 (단위:만명)",
     xlab = "년도",
        las=1
     )
```

## 서울시 top,wost5 인구

2021년 상위 5개 자치구 확인

```{r}
seoul_popul_top5 <- as.data.frame(t(seoul_popul))[,-1] 

seoul_popul_top5 <- seoul_popul[,c(colnames(seoul_rent_top5))]
rownames(seoul_popul_top5) <- c(2016:2021)

for (i in 1:length(seoul_popul_top5)) {
  seoul_popul_top5[,i] <- as.numeric(seoul_popul_top5[,i]) 
}
seoul_popul_top5
```

## 서울시top5인구

### 전년도별 top5 인구상승률

```{r}
seoul_popul_top5 <-  as.data.frame(t(seoul_popul_top5)) 

seoul_popul_top5_rise <- c()
seoul_popul_top5_rise <- as.data.frame(round((seoul_popul_top5[,2] -seoul_popul_top5[,1])/seoul_popul_top5[,1]*100,2)) 

for (i in 2:5) {
  seoul_popul_top5_rise[,i] <- as.data.frame(round((seoul_popul_top5[,(i+1)] -seoul_popul_top5[,i])/seoul_popul_top5[,i]*100,2)) 
}

colnames(seoul_popul_top5_rise) <- colnames(seoul_popul_top5[,-1])
rownames(seoul_popul_top5_rise) <- rownames(seoul_popul_top5)

seoul_popul_top5 <- as.data.frame(t(seoul_popul_top5_rise))
seoul_popul_top5
```

```{r}
par(family = "AppleGothic")
plot(seoul_popul_top5$강남구~rownames(seoul_popul_top5),
     type = "l",
     col = 'red',
     main = "2017~2021 서울시 자치구 top5 전년대비 인구상승률",
     ylim = c(-3,3),
     ylab = "상승률 (단위:%)",
     xlab = "년도",
        las=1
)
lines(seoul_popul_top5$서초구~rownames(seoul_popul_top5),
  col = 'blue'
)
lines(seoul_popul_top5$용산구~rownames(seoul_popul_top5),
  col = 'green'
)
lines(seoul_popul_top5$성동구~rownames(seoul_popul_top5),
  col = 'orange'
)
lines(seoul_popul_top5$중구~rownames(seoul_popul_top5),
  col = 'skyblue'
)
legend(2020,3,
  c(colnames(seoul_popul_top5)),
  col = c("red",'blue','green','purple','orange'),
  lty = c(1,1,1,1,1),
  cex = 0.7
)
```

### 전년도별 wost5 인구상승률

```{r}
seoul_popul_wost5 <- as.data.frame(t(seoul_popul))[,-1] 

seoul_popul_wost5 <- seoul_popul[,c(colnames(seoul_rent_wost5))]
rownames(seoul_popul_wost5) <- c(2016:2021)

for (i in 1:length(seoul_popul_wost5)) {
  seoul_popul_wost5[,i] <- as.numeric(seoul_popul_wost5[,i]) 
}
seoul_popul_wost5
```

```{r}
seoul_popul_wost5 <-  as.data.frame(t(seoul_popul_wost5)) 

seoul_popul_wost5_rise <- c()
seoul_popul_wost5_rise <- as.data.frame(round((seoul_popul_wost5[,2] -seoul_popul_wost5[,1])/seoul_popul_wost5[,1]*100,2)) 

for (i in 2:5) {
  seoul_popul_wost5_rise[,i] <- as.data.frame(round((seoul_popul_wost5[,(i+1)] -seoul_popul_wost5[,i])/seoul_popul_wost5[,i]*100,2)) 
}

colnames(seoul_popul_wost5_rise) <- colnames(seoul_popul_wost5[,-1])
rownames(seoul_popul_wost5_rise) <- rownames(seoul_popul_wost5)

seoul_popul_wost5 <- as.data.frame(t(seoul_popul_wost5_rise))
seoul_popul_wost5
```

```{r}
par(family = "AppleGothic")
plot(seoul_popul_wost5$금천구~rownames(seoul_popul_wost5),
     type = "l",
     col = 'red',
     main = "2017~2021 서울시 자치구 worst5 전년대비 인구상승률",
     ylim = c(-3,2),
     ylab = "상승률 (단위:%)",
     xlab = "년도",
        las=1
)
lines(seoul_popul_wost5$구로구~rownames(seoul_popul_wost5),
  col = 'blue'
)
lines(seoul_popul_wost5$강북구~rownames(seoul_popul_wost5),
  col = 'green'
)
lines(seoul_popul_wost5$관악구~rownames(seoul_popul_wost5),
  col = 'orange'
)
lines(seoul_popul_wost5$중랑구~rownames(seoul_popul_wost5),
  col = 'skyblue'
)
legend(2020,2,
  c(colnames(seoul_popul_wost5)),
  col = c("red",'blue','green','purple','orange'),
  lty = c(1,1,1,1,1),
  cex = 0.7
)
```

```{r}
round(cor(seoul_popul_total,seoul_rent_top5),2)
round(cor(seoul_popul_total,seoul_rent_wost5),2)
```
