# 데이터 시각화2

선굵기 변경하기

```{r}
x <- c(1,3,5,2,9,10)
plot(x,
     type = "b",
     col = c(rep("black",5),'red'),
     lwd = c(rep("1",5),"3")
     
     )
```

### 한 화면에 차트 여러개 그려서 비교하기

```{r}
price <- runif(10,1,100)
plot(price)
```

```{r}
par(mfrow = c(2,2))
plot(price, type = "l")
plot(price, type = "o")
plot(price, type = "h")
plot(price, type = "s")
```

pch 속성으로 그리기

```{r}
par(mfrow = c(2,2))
    plot((price),type = "o",pch = 5)
    plot((price),type = "o",pch = 15)
    plot((price),type = "o",pch = 20,col = "blue")
    plot((price),type = "o",pch = c(rep(20,8), 15,15),
         col= " orange",
         cex = c(rep(1,8),3,1)
         )
```

### 중첩 자료 시각화

```{r}
x <- c(1,2,3,4,2,4)
y <- rep(2,6)
plot(x,y)
```

```{r}
table(x,y)
```

method#1

```{r}
xy.df <- as.data.frame(table(x,y))
xy.df
plot(x,y,
     pch = 15,
     cex = 2 * xy.df$Freq
     )
```

### method 2

```{r}
x <- c(1,1,1,2,2,2,2,2,2,3,3,4,5,6)
y <- c(1,1,4,2,3,2,2,2,3,2,1,1,1,1)
zz <- data.frame(x,y)
sunflowerplot(zz)
```

sunflowerplot으로 iris의 sepal.length와 sepal.width의 산포도 그리기

```{r}
sunflowerplot(iris$Sepal.Length,iris$Sepal.Width)
```

### chart2개를 겹쳐서 출력하기

```{r}
x <- 1:10
mycol <- rgb(0,0,1,seq(0,1,0.1))

dotchart(x,
         color = 'red'
         )
par(new = T)
barplot(x,
        col = mycol
        )
```

# 상자 수염 그래프

:이상치 확인

```{r}
abc <- c(110, 300, 150, 280, 310)
boxplot(abc)
```

```{r}
summary(abc)
```

```{r}
abc <- c(110, 300, 150, 280, 310)
boxplot(abc,
        col = "yellow",
        horizontal = T
        )
#이상치와 결측치는 다른것이다
#이상치가 있을경우 이상치는 제외하고 데이터를 쓴다.
#최소 최대 1사 3사 중앙값이 나온다
#결측치와 이상치의 합이 40%가 넘어가면 해당 컬럼은 사용이 불가능하다
```

```{r}
def <- c(1,1,1,1,1,2,5)
summary(def)
```

```{r}
boxplot(def)
```

자동차 제동거리

```{r}
head(cars)
```

```{r}
str(cars)
```

```{r}
plot(cars$speed,cars$dist)
```

```{r}
#빈도수는 히스토그램
hist(cars$dist)
```

```{r}
boxplot(cars$dist)
```

# 차트 디ㅂ자인

```{r}
par(family = "AppleGothic")
x <- c(1,3,6,8,9)
y <- c(12,56,78,32,9)
plot(x,y)

#(3,3)과 (4,4)를 연결하는 선분 그리기
segments(6,78,8,32, col = "red")

#화살표 그리기
arrows(3,56, 1,12, col="blue")
arrows(3,33, 1,12)

#글자쓰기
text(4,40, "This is a sample", srt=50)

#테두리 활용하기
mtext("Character", side = 4, adj = 1)

#테두리 그리기
box(lty = 1, col = 'red')

#사각형 그리기 (4,20),(6,30)의 사각형 그리기
rect(4,20, 6,30, density = 30, col = 'red')

# x축 추가, 40위치에 0~10까지 표시하고 색은 빨간색
axis(1, pos = 40,at=0:10, col = 'red')

# y축 추가, x축의 6 위ㅍ치에 20~60까지 표시하고 색은 파란색
axis(2,pos=6, at=20:60, col = 'blue')
```

## 투표수가 높은 시군구의 후보별 득표수의 막대그래프에 시군구별 투표수 표시하기

```{r}
election <- read.csv("./Data/election_2022.csv")
election
```

```{r}
arrange(election,desc(election$투표수))
election

top4_sigungu <- arrange(election,desc(election$투표수))[1:5,c(1:2,5:7)]

top4_sigungu_label <- paste(top4_sigungu$광역시도,top4_sigungu$시군구)
top4_sigungu_label
top4_sigungu_barplot
top4_sigungu_barplot <- t(top4_sigungu[,-c(1:2)])
top4_sigungu_sum <- as.data.frame(top4_sigungu_barplot)
for (i in 1:ncol(top4_sigungu_sum)) {
  top4_sigungu_sum[,i] <- sum(top4_sigungu_sum[,i])
}
top4_sigungu_sum <- top4_sigungu_sum[1,]
```

```{r}
par(family="AppleGothic")
options(scipen = 100)
barplot(top4_sigungu_barplot,
        ylim = c(0,600000),
        names = top4_sigungu_label,
        col = c("skyblue","red","yellow"),
        cex.axis = 0.5,
        cex.names = 0.5,
        legend.text = T,
        main = "투표수 높은 지역의 후보별 투표수",
  
        )
xlab <- c()
xlab <- top4_sigungu_barplot[1,]/2

text(c(0.7,1.9,3.1,4.3,5.5),xlab, top4_sigungu_barplot[1,], srt=0, cex = 0.8)
xlab <- top4_sigungu_barplot[1,]
ylab <- xlab + top4_sigungu_barplot[2,] - (top4_sigungu_barplot[2,]/2)

text(c(0.7,1.9,3.1,4.3,5.5),ylab, top4_sigungu_barplot[2,], srt=0, cex = 0.8)
xlab <- xlab + top4_sigungu_barplot[2,]
ylab <- xlab + top4_sigungu_barplot[3,] - (top4_sigungu_barplot[3,]/2)

text(c(0.7,1.9,3.1,4.3,5.5),ylab, top4_sigungu_barplot[3,], srt=0, cex = 0.8)

#text(c(0.7,1.9,3.1,4.3,5.5),(top4_sigungu_sum*1.05), top4_sigungu_sum, srt=0, cex = 0.8)
#for (i in 1:nrow(top4_sigungu_barplot)) {
#  xlab <- top4_sigungu_barplot[i,]
#  text(c(0.7,1.9,3.1,4.3,5.5),xlab, top4_sigungu_barplot[i,], srt=0, cex = 0.8)
#  xlab <-  xlab + top4_sigungu_barplot[i,]
#}


```

qplot()을 이용한 산점도

```{r}
install.packages("ggplot2")
library(ggplot2)


```

```{r}
qplot(Sepal.Length,Petal.Length,
      data = iris, 
      col = Species,
      size = Petal.Width
      )
```

# 수학 함수의 시각화

y = x\^2

```{r}
f <- function(x){
  y = x ^ 2
  return(y)
}
```

```{r}
x <- 1:3
f(x)
```

```{r}
x <- seq(-5,5,0.1)
plot(x, f(x),
     type = "l"
     )
```

y = x\^2 + 2x +3

```{r}
f2 <- function(x){
  y = x^2 + (2*x) +3
  return(y)
}
```

```{r}
x <- seq(-6,4,0.1)
plot(x, f2(x),
     type = "l"
     )
```
