# 회귀분석

알고싶은 것이 종속변수로 들어간다

단순회귀 분석과 다중 회귀 분석

```{r}
regression <- read.csv("./Data/regression.csv")
head(regression)
```

```{r}
str(regression)
```

```{r}
summary(regression$Height)
summary((regression$Weight))
```

```{r}
plot(regression$Height,regression$Weight)
```

```{r}
cor(regression$Height,regression$Weight)
```

```{r}
plot(regression$Weight~regression$Height)

#회귀식 : lm(종속변수 ~ 독립변수)
r <- lm(regression$Weight ~ regression$Height)
abline(r, col = "red")
```

분석결과

```{r}
summary(r)
```

p-value: \< 2.2e-16 \< 0.05

Adjusted R-squared: 0.9333 \<- 예측력

Residual standard error: 6.355 \<- 표준오차 플러스마이너스 6.35

\*가 높을수록 중요한 데이터이다

```{r}
r
```

y = ax + b

몸무게 = 0.6147 \* 키 +( -40.8659)

키가 170cm인 사람의 몸무게를 예측

```{r}
a <- 170
0.6147 * a +( -40.8659)

#표준오차를 적용한 키가 170인 사람의 몸무게
paste(0.6147 * a +( -40.8659) - 6.355, "~",0.6147 * a +( -40.8659)+6.355)
```

```{r}
iq <- read.csv("./Data/IQ.csv")
head(iq)
```

```{r}
str(iq)
```

### (1)IQ가 126인 사람의 성적을 예측해보세요

```{r}
cor(iq$IQ,iq$성적)
```

```{r}
plot(iq$성적~iq$IQ)

r <- lm(iq$성적 ~ iq$IQ)

abline(r,col="red")
```

```{r}
r
```

```{r}
summary(r)
```

```{r}
score <- 126
(0.6714 * score + (-5.2918))
paste(0.6714 * score -3.322,"~",0.6714 * score+3.322)
```

### 성적과 가장 관련이 깊은 항목은?

```{r}
a <-cor(iq[,-1])

```

### 학원을 몇군데 다녀야 90점이 될까

```{r}
plot(iq$다니는.학원수 ~ iq$성적)

iqlm <- lm(iq$다니는.학원수 ~ iq$성적)

abline(iqlm,col="red")
```

```{r}
summary(iqlm)
```

```{r}
hack <- 90

paste(0.1241*hack+(-7.89163)-0.7882,"~",0.1241*hack+(-7.89163)+0.7882)
```

# 다중 회귀 분석

여러개의 항목들로 구성된 식으로 예측하는 방법

```{r}
data("attitude")
help("attitude")
```

```{r}
head(attitude)
```

```{r}
str(attitude)
```

```{r}
plot(attitude)
```

rating을 제외한 변수들이 rating에 어떤 영향을 미치는지 회귀분석으로 분석

```{r}
model <- lm(rating ~ .,data=attitude)
model
```

```{r}
summary(model)
```

```{r}
cor(attitude)
```

예측력을 향상

sammary에서 관련성없는 컬럼을 제거해줌

```{r}
reduced <- step(model,direction = "backward")
```

step에서 정의가 된것이라 \*이 없어도 사용해야한다.

```{r}
summary(reduced)
```

```{r}
reduced
```

# iris에 대한 다중 회귀분석

```{r}

irismodel <- lm(as.numeric(Species) ~ ., data = iris)


irismodel
```

```{r}
irismodel <-step(irismodel,direction = "backward")
```

```{r}
summary(irismodel)
```

```{r}
f <- function(x1,x2,x3){
  y = (-0.13624*x1)+(0.25213*x2)+(0.58689*x3)+1.14469
  return(y)
}
```

```{r}
f(5.9,5.1,1.8)
```
